services:
  load-balancer:
    build: .
    depends_on:
      backend-1:
        condition: service_started
      backend-2:
        condition: service_started
      backend-3:
        condition: service_started
    ports:
      - "8081:8080"
    environment:
      CONFIG_PATH: /app/config.json
    networks:
      - lbnet

  backend-1:
    image: nginx:alpine
    volumes:
      - ./nginx/echo.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "9001:80"
    networks:
      - lbnet

  backend-2:
    image: nginx:alpine
    volumes:
      - ./nginx/echo.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "9002:80"
    networks:
      - lbnet

  backend-3:
    image: nginx:alpine
    volumes:
      - ./nginx/echo.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "9003:80"
    networks:
      - lbnet

  loadtest-ab:
    image: jordi/ab
    profiles:
      - loadtest-ab
    depends_on:
      load-balancer:
        condition: service_started
    networks:
      - lbnet
    entrypoint: ["ab"]
    command:
      - "-H"
      - "X-API-Key: clientX"
      - "-n" 
      - "5000" 
      - "-c" 
      - "1000"
      - "http://load-balancer:8080/"

  loadtest-vegeta:
    image: peterevans/vegeta
    profiles:
      - loadtest-vegeta
    depends_on:
      load-balancer:
        condition: service_started
    networks:
      - lbnet
    volumes:
      - ./vegeta/targets.txt:/targets.txt:ro
      - ./vegeta/reports:/reports
    entrypoint: ["sh", "-c"]
    command:
      - |
        vegeta attack \
          -targets=/targets.txt \
          -rate=1000 \
          -duration=10s \
        | tee /reports/results.bin \
        | vegeta report --type=text \
        && vegeta plot /reports/results.bin > /reports/plot.html

networks:
  lbnet:
    driver: bridge
