version: "3.8"

services:
  clients-db:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: loadbalancer
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - lbnet

  load-balancer:
    build: .
    depends_on:
      - clients-db
      - backend-1
      - backend-2
      - backend-3
    ports:
      - "8080:8080"
    environment:
      CONFIG_PATH: /app/config.json
    networks:
      - lbnet

  backend-1:
    image: nginx:alpine
    volumes:
      - ./nginx/echo.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "9001:80"
    networks:
      - lbnet

  backend-2:
    image: nginx:alpine
    volumes:
      - ./nginx/echo.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "9002:80"
    networks:
      - lbnet

  backend-3:
    image: nginx:alpine
    volumes:
      - ./nginx/echo.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "9003:80"
    networks:
      - lbnet

volumes:
  db-data:

networks:
  lbnet:
    driver: bridge
