services:
  load-balancer:
    build: .
    depends_on:
      backend-1:
        condition: service_started
      backend-2:
        condition: service_started
      backend-3:
        condition: service_started
    ports:
      - "8081:8080"
    environment:
      CONFIG_PATH: /app/config.json
    networks:
      - lbnet

  backend-1:
    image: nginx:alpine
    volumes:
      - ./nginx/echo.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "9001:80"
    networks:
      - lbnet

  backend-2:
    image: nginx:alpine
    volumes:
      - ./nginx/echo.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "9002:80"
    networks:
      - lbnet

  backend-3:
    image: nginx:alpine
    volumes:
      - ./nginx/echo.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "9003:80"
    networks:
      - lbnet

networks:
  lbnet:
    driver: bridge
